# Generated by Django 3.2.15 on 2022-11-30 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0039_auto_20220506_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadparallelismlimit',
            name='max_number',
            field=models.PositiveSmallIntegerField(default=5, help_text='The maximum number of parallel uploads (0 to 32767).'),
        ),
    ]
